#!/usr/bin/env zsh
#
# none icon set — no icons, text only
# ideal for CI, logs, and minimal output
#

SHUI_ICON_SUCCESS=""
SHUI_ICON_ERROR=""
SHUI_ICON_WARNING=""
SHUI_ICON_INFO=""
SHUI_ICON_BULLET=""
SHUI_ICON_ARROW=""
SHUI_ICON_CHECK=""
SHUI_ICON_CROSS=""

SHUI_ICON_CHECKMARK=""
SHUI_ICON_QUESTION=""
SHUI_ICON_CHECK_ALT=""
SHUI_ICON_CROSS_ALT=""

SHUI_ICON_ARROW_RIGHT=""
SHUI_ICON_ARROW_LEFT=""
SHUI_ICON_ARROW_UP=""
SHUI_ICON_ARROW_DOWN=""

SHUI_ICON_DOWNLOAD=""
SHUI_ICON_UPLOAD=""
SHUI_ICON_DELETE=""
SHUI_ICON_EDIT=""
SHUI_ICON_SEARCH=""
SHUI_ICON_SETTINGS=""
SHUI_ICON_REFRESH=""
SHUI_ICON_LOCK=""
SHUI_ICON_UNLOCK=""

SHUI_ICON_TOOLS=""
SHUI_ICON_COMPUTER=""
SHUI_ICON_PLUG=""
SHUI_ICON_INSTALL=""
SHUI_ICON_BOLT=""
SHUI_ICON_ROCKET=""
SHUI_ICON_CLOCK=""
SHUI_ICON_FIRE=""
SHUI_ICON_STAR=""
SHUI_ICON_HEART=""
SHUI_ICON_THUMBS_UP=""

SHUI_ICON_INFO_BRACKET=""
SHUI_ICON_WARN_BRACKET=""
SHUI_ICON_USER_BRACKET=""
SHUI_ICON_INPUT_BRACKET=""

SHUI_ICON_STARTER=""
SHUI_ICON_PROMPT=""
SHUI_ICON_PALETTE=""
SHUI_ICON_GLOBE=""
SHUI_ICON_TABLE=""
SHUI_ICON_FORWARD=""
SHUI_ICON_CHART=""
SHUI_ICON_BUG=""
SHUI_ICON_LOADING=""

SHUI_ICON_CIRCLE=""
SHUI_ICON_CIRCLE_EMPTY=""
SHUI_ICON_SQUARE=""
SHUI_ICON_SQUARE_EMPTY=""
SHUI_ICON_TRIANGLE=""
SHUI_ICON_DIAMOND=""
